// Generated by https://quicktype.io

export interface Services {
  data: ServicesDatum[];
  meta: Meta;
}

export interface ServicesDatum {
  id:         number;
  attributes: Attributes;
}

export interface Attributes {
  title:       string;
  desc:        string;
  price:       number;
  createdAt:   Date;
  updatedAt:   Date;
  publishedAt: Date;
  image:       Image;
  benefits:    Benefits;
  categories:  Benefits;
}

export interface Benefits {
  data: BenefitsDatum[];
}

export interface BenefitsDatum {
  id:         number;
  attributes: FluffyAttributes;
}

export interface FluffyAttributes {
  desc:       string;
  createdAt:   Date;
  updatedAt:   Date;
  publishedAt: Date;
}

export interface Image {
  data: Data;
}

export interface Data {
  id:         number;
  attributes: DataAttributes;
}

export interface DataAttributes {
  name:              string;
  alternativeText:   null;
  caption:           null;
  width:             number;
  height:            number;
  formats:           Formats;
  hash:              string;
  ext:               string;
  mime:              string;
  size:              number;
  url:               string;
  previewUrl:        null;
  provider:          string;
  provider_metadata: null;
  createdAt:         Date;
  updatedAt:         Date;
}

export interface Formats {
  thumbnail: Medium;
  medium:    Medium;
  small:     Medium;
}

export interface Medium {
  name:   string;
  hash:   string;
  ext:    string;
  mime:   string;
  path:   null;
  width:  number;
  height: number;
  size:   number;
  url:    string;
}

export interface Meta {
  pagination: Pagination;
}

export interface Pagination {
  page:      number;
  pageSize:  number;
  pageCount: number;
  total:     number;
}


// Generated by https://quicktype.io

export interface Benefits {
  data: BenefitsDatum[];
  meta: Meta;
}



// Generated by https://quicktype.io

export interface Teams {
  data: TeamsDatum[];
  meta: Meta;
}

export interface TeamsDatum {
  id:         number;
  attributes: PurpleAttributes;
}

export interface PurpleAttributes {
  name:            string;
  desc:            string;
  createdAt:       Date;
  updatedAt:       Date;
  publishedAt:     Date;
  image:           Image;
  social_profiles: SocialProfiles;
}

export interface Image {
  data: Data;
}

export interface Data {
  id:         number;
  attributes: DataAttributes;
}

export interface DataAttributes {
  name:              string;
  alternativeText:   null;
  caption:           null;
  width:             number;
  height:            number;
  formats:           Formats;
  hash:              string;
  ext:               string;
  mime:              string;
  size:              number;
  url:               string;
  previewUrl:        null;
  provider:          string;
  provider_metadata: null;
  createdAt:         Date;
  updatedAt:         Date;
}

export interface Formats {
  thumbnail: Large;
  small:     Large;
  medium:    Large;
  large:     Large;
}

export interface Large {
  name:   string;
  hash:   string;
  ext:    string;
  mime:   string;
  path:   null;
  width:  number;
  height: number;
  size:   number;
  url:    string;
}

export interface SocialProfiles {
  data: SocialProfilesDatum[];
}

export interface SocialProfilesDatum {
  id:         number;
  attributes: FluffyAttributes;
}

export interface FluffyAttributes {
  red:         string;
  icono:       string;
  createdAt:   Date;
  updatedAt:   Date;
  publishedAt: Date;
}

export interface Meta {
  pagination: Pagination;
}

export interface Pagination {
  page:      number;
  pageSize:  number;
  pageCount: number;
  total:     number;
}


// Generated by https://quicktype.io

export interface HostVideo {
  data: Datum[];
  meta: Meta;
}

export interface Datum {
  id:         number;
  attributes: Attributes;
}

export interface Attributes {
  title:        string;
  desc:         string;
  url:          string;
  creationDate: null;
  createdAt:    Date;
  updatedAt:    Date;
  publishedAt:  Date;
}

export interface Meta {
  pagination: Pagination;
}

export interface Pagination {
  page:      number;
  pageSize:  number;
  pageCount: number;
  total:     number;
}



// Generated by https://quicktype.io

export interface Videos {
  data: Datum[];
  meta: Meta;
}

export interface Datum {
  id:         number;
  attributes: Attributes;
}

export interface Attributes {
  title:       string;
  desc:        string;
  url:         string;
  createdAt:   Date;
  updatedAt:   Date;
  publishedAt: Date;
}

export interface Meta {
  pagination: Pagination;
}

export interface Pagination {
  page:      number;
  pageSize:  number;
  pageCount: number;
  total:     number;
}
